networks:
  dosportal_internal:
    driver: bridge

services:
  db_dosportal:
    image: postgis/postgis
    env_file:
      - .env
    volumes:
      - ./data/dosportal/db_pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-dosportal}
      - POSTGRES_USER=${POSTGRES_USER:-dosportal_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-dosportal_password}
    networks:
      - dosportal_internal

  backend:
    image: ghcr.io/universalscientifictechnologies/dosportal-backend:dev
    env_file:
      - .env
    depends_on:
      - db_dosportal
      - redis
      - minio
    networks:
      - dosportal_internal
      
  worker:
    image: ghcr.io/universalscientifictechnologies/dosportal-backend:dev
    entrypoint: python3 manage.py qcluster
    env_file:
      - .env
    depends_on:
      - backend
      - db_dosportal
      - redis
    networks:
      - dosportal_internal

  redis:
    image: redis
    depends_on:
      - db_dosportal
    networks:
      - dosportal_internal

  minio:
    image: minio/minio
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data
    networks:
      - dosportal_internal

  frontend:
    image: ghcr.io/universalscientifictechnologies/dosportal-frontend:dev
    depends_on:
      - backend
    networks:
      - dosportal_internal
      
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    ports:
      - "8080:80"
    networks:
      - dosportal_internal

ls
