networks:
  inet:
    driver: bridge
  default:
    driver: bridge

services:
  db_dosportal:
    image: postgis/postgis
    env_file:
      - .env
    volumes:
      - ./data/dosportal/db_pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-dosportal}
      - POSTGRES_USER=${POSTGRES_USER:-dosportal_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-dosportal_password}
    networks:
      - inet

  backend:
    image: ${BACKEND_IMAGE:-ghcr.io/universalscientifictechnologies/dosportal-backend:master}
    env_file:
      - .env
    depends_on:
      - db_dosportal
      - redis
      - minio
    networks:
      - inet

  worker:
    image: ${BACKEND_IMAGE:-ghcr.io/universalscientifictechnologies/dosportal-backend:master}
    entrypoint: ["python", "manage.py", "qcluster"]
    env_file:
      - .env
    depends_on:
      - backend
      - db_dosportal
      - redis
    networks:
      - inet

  redis:
    image: redis
    depends_on:
      - db_dosportal
    networks:
      - inet

  minio:
    image: minio/minio
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
      MINIO_BROWSER_REDIRECT_URL: ${MINIO_BROWSER_REDIRECT_URL}
      MINIO_SERVER_URL: ${MINIO_SERVER_URL}
      MINIO_BROWSER_REDIRECT: "on"
    command: server /data --console-address ":9001" --address ":9000"
    volumes:
      - ./data/minio:/data
    networks:
      - inet

  frontend:
    image: ${FRONTEND_IMAGE:-ghcr.io/universalscientifictechnologies/dosportal-frontend:master}
    depends_on:
      - backend
    networks:
      - inet

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx_config/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - inet
