networks:
  dosportal_internal:
    driver: bridge

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    image: dosportal-backend:local
    env_file:
      - .env
    volumes:
      - ./DOSPORTAL:/app/DOSPORTAL
    depends_on:
      - db_dosportal
      - redis
      - minio
    ports:
      - "8000:8000"
    networks:
      - dosportal_internal

  frontend:
    build:
      context: .
      dockerfile: frontend.dev.Dockerfile
    image: dosportal-frontend:local
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - dosportal_internal

  worker:
    image: dosportal-backend:local
    entrypoint: python3 manage.py qcluster
    env_file:
      - .env
    depends_on:
      - backend
      - db_dosportal
      - redis
    networks:
      - dosportal_internal

  redis:
    image: redis
    depends_on:
      - db_dosportal
    networks:
      - dosportal_internal

  db_dosportal:
    image: postgis/postgis
    env_file:
      - .env
    volumes:
      - ./data/db_pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-dosportal}
      - POSTGRES_USER=${POSTGRES_USER:-dosportal_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-dosportal_password}
    networks:
      - dosportal_internal

  minio:
    image: minio/minio
    env_file:
      - .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data
    networks:
      - dosportal_internal
